"""initial migration

Revision ID: 7cd2adfa37c5
Revises: 
Create Date: 2026-02-09 15:52:03.935849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cd2adfa37c5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('billing', 'technical', 'feature', 'general', name='category'), nullable=True),
    sa.Column('sentiment_score', sa.Integer(), nullable=True),
    sa.Column('urgency', sa.Enum('high', 'medium', 'low', name='urgency'), nullable=True),
    sa.Column('ai_draft', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processed', 'resolved', 'error', name='ticketstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_status_created', 'tickets', ['status', 'created_at'], unique=False)
    op.create_index('idx_urgency_status', 'tickets', ['urgency', 'status'], unique=False)
    op.create_index(op.f('ix_tickets_category'), 'tickets', ['category'], unique=False)
    op.create_index(op.f('ix_tickets_created_at'), 'tickets', ['created_at'], unique=False)
    op.create_index(op.f('ix_tickets_email'), 'tickets', ['email'], unique=False)
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_index(op.f('ix_tickets_urgency'), 'tickets', ['urgency'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_urgency'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_email'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_created_at'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_category'), table_name='tickets')
    op.drop_index('idx_urgency_status', table_name='tickets')
    op.drop_index('idx_status_created', table_name='tickets')
    op.drop_table('tickets')
    # ### end Alembic commands ###
