"""create tickets table

Revision ID: 951ec74927bc
Revises: 
Create Date: 2026-02-09 11:20:01.525034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '951ec74927bc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('billing', 'technical', 'feature', name='category'), nullable=True),
    sa.Column('sentiment_score', sa.Integer(), nullable=True),
    sa.Column('urgency', sa.Enum('high', 'medium', 'low', name='urgency'), nullable=True),
    sa.Column('ai_draft', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processed', 'resolved', 'error', name='ticketstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    # ### end Alembic commands ###
